// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need the session pooler (port 5432): it supports the
    // session-level advisory locks `prisma migrate deploy` takes. Runtime
    // queries use DATABASE_URL (transaction pooler, port 6543) instead,
    // see src/lib/db.ts — the session pooler caps concurrent clients at 15,
    // too few for serverless function instances.
    url: process.env["MIGRATE_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
