import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

// Ruta temporal para cargar los datos iniciales de los planes SST y MA.
// Protegida con token de una sola vez. BORRAR después de usarla.

const TOKEN = process.env.SEED_TOKEN;

const SST = [
  { codigoExterno: "1", eje: "Liderazgo y gobernanza", actividad: "Diagnóstico de brechas SG-SST", descripcion: "Evaluar brechas ISO 45001, DS N°44, Ley 16.744 y requisitos internos.", responsable: "EHS", inicio: "2026-08-05", fin: "2026-09-15", frecuencia: "Anual", evidencia: "Informe diagnóstico y plan de acción", kpi: "% brechas evaluadas", meta: "100%", prioridad: "Alta", estado: "En curso", avance: 0.35 },
  { codigoExterno: "2", eje: "Liderazgo y gobernanza", actividad: "Aprobación de política SST", descripcion: "Actualizar, validar y aprobar política SST con alta dirección.", responsable: "Alta Dirección / EHS", inicio: "2026-09-01", fin: "2026-09-30", frecuencia: "Anual", evidencia: "Política firmada y difundida", kpi: "Política aprobada", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "3", eje: "Cumplimiento legal", actividad: "Matriz legal SST", descripcion: "Actualizar requisitos legales y evaluar cumplimiento.", responsable: "EHS", inicio: "2026-09-01", fin: "2026-09-30", frecuencia: "Semestral", evidencia: "Matriz legal y plan de brechas", kpi: "% cumplimiento legal", meta: "≥ 90%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "4", eje: "Planificación de riesgos", actividad: "Actualización MIPER", descripcion: "Actualizar peligros, riesgos, controles, residuos de riesgo y responsables.", responsable: "EHS / Supervisores / Trabajadores", inicio: "2026-09-15", fin: "2026-10-31", frecuencia: "Semestral", evidencia: "MIPER actualizada", kpi: "% áreas con MIPER vigente", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "5", eje: "Planificación de riesgos", actividad: "Definición de riesgos críticos", descripcion: "Identificar tareas críticas y controles críticos verificables.", responsable: "EHS / Operaciones", inicio: "2026-10-01", fin: "2026-10-31", frecuencia: "Anual", evidencia: "Lista de riesgos y controles críticos", kpi: "% controles críticos definidos", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "6", eje: "Competencia y formación", actividad: "Matriz de capacitación SST", descripcion: "Definir capacitación por cargo, riesgo y requisito legal.", responsable: "EHS / RR.HH.", inicio: "2026-10-01", fin: "2026-11-15", frecuencia: "Anual", evidencia: "Matriz y plan de capacitación", kpi: "% matriz completada", meta: "100%", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "7", eje: "Competencia y formación", actividad: "Inducción SST trabajadores y contratistas", descripcion: "Ejecutar inducción a ingresos, visitas y contratistas.", responsable: "EHS / Supervisores", inicio: "2026-08-05", fin: "2027-12-31", frecuencia: "Continuo", evidencia: "Registros de inducción", kpi: "% inducciones realizadas", meta: "100%", prioridad: "Alta", estado: "En curso", avance: 0.2 },
  { codigoExterno: "8", eje: "Control operacional", actividad: "Inspecciones planeadas", descripcion: "Realizar inspecciones mensuales por área y seguimiento de hallazgos.", responsable: "Supervisores / CPHS / EHS", inicio: "2026-09-01", fin: "2027-12-31", frecuencia: "Mensual", evidencia: "Checklists e informes", kpi: "% inspecciones realizadas", meta: "≥ 90%", prioridad: "Alta", estado: "En curso", avance: 0.15 },
  { codigoExterno: "9", eje: "Participación y comunicación", actividad: "Reportabilidad preventiva", descripcion: "Canalizar reportes de peligros, incidentes, oportunidades y sugerencias.", responsable: "Todos / EHS", inicio: "2026-08-05", fin: "2027-12-31", frecuencia: "Mensual", evidencia: "Registro de reportes y cierre", kpi: "% reportes cerrados", meta: "≥ 80%", prioridad: "Alta", estado: "En curso", avance: 0.25 },
  { codigoExterno: "10", eje: "Control operacional", actividad: "Permisos de trabajo y controles críticos", descripcion: "Auditar permisos y verificar controles en tareas críticas.", responsable: "EHS / Supervisores", inicio: "2026-11-01", fin: "2027-12-31", frecuencia: "Trimestral", evidencia: "Informes de verificación", kpi: "% controles auditados", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "11", eje: "Contratistas", actividad: "Gestión SST de contratistas", descripcion: "Evaluar documentación, inducción, controles y desempeño de contratistas.", responsable: "EHS / Administradores de contrato", inicio: "2027-01-01", fin: "2027-12-31", frecuencia: "Trimestral", evidencia: "Evaluación y evidencias contratistas", kpi: "% contratistas evaluados", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "12", eje: "Emergencias", actividad: "Actualización Plan de Emergencias", descripcion: "Revisar roles, recursos y procedimientos del plan de emergencias.", responsable: "EHS / Brigada", inicio: "2026-11-01", fin: "2026-12-31", frecuencia: "Anual", evidencia: "Plan actualizado y difundido", kpi: "Plan aprobado", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "13", eje: "Emergencias", actividad: "Simulacro de emergencia T1", descripcion: "Ejecutar simulacro de evacuación en turno diurno.", responsable: "EHS / Brigada", inicio: "2026-11-01", fin: "2026-11-30", frecuencia: "Semestral", evidencia: "Informe de simulacro", kpi: "Nro simulacros realizados", meta: "2", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "14", eje: "Emergencias", actividad: "Simulacro integral T3", descripcion: "Ejecutar simulacro en turno nocturno o rotativo.", responsable: "EHS / Brigada", inicio: "2027-05-01", fin: "2027-05-31", frecuencia: "Anual", evidencia: "Informe de simulacro", kpi: "Nro simulacros realizados", meta: "2", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "15", eje: "Salud ocupacional", actividad: "Campaña de ergonomía y salud ocupacional", descripcion: "Talleres, evaluaciones y mejoras ergonómicas.", responsable: "EHS / RRHH / Mutual", inicio: "2027-03-01", fin: "2027-05-31", frecuencia: "Anual", evidencia: "Registros y evaluaciones", kpi: "% trabajadores capacitados", meta: "≥ 80%", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "16", eje: "Incidentes y mejora", actividad: "Procedimiento de investigación de incidentes", descripcion: "Crear o actualizar procedimiento y capacitar a investigadores.", responsable: "EHS / Supervisores", inicio: "2026-10-01", fin: "2026-11-30", frecuencia: "Anual", evidencia: "Procedimiento publicado y capacitación", kpi: "% incidentes investigados", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "17", eje: "Incidentes y mejora", actividad: "Gestión de acciones correctivas", descripcion: "Registrar, asignar, seguir y cerrar CAPA de hallazgos e incidentes.", responsable: "EHS / Responsables de área", inicio: "2026-08-05", fin: "2027-12-31", frecuencia: "Mensual", evidencia: "Registro CAPA y tasa de cierre", kpi: "% CAPA cerradas en plazo", meta: "≥ 85%", prioridad: "Alta", estado: "En curso", avance: 0.3 },
  { codigoExterno: "18", eje: "Verificación", actividad: "Auditoría interna parcial", descripcion: "Auditoría enfocada en cláusulas críticas ISO 45001.", responsable: "EHS / Auditor interno", inicio: "2027-03-01", fin: "2027-04-30", frecuencia: "Anual", evidencia: "Informe de auditoría", kpi: "% cláusulas auditadas", meta: "100%", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "19", eje: "Cumplimiento legal", actividad: "Evaluación legal semestral 2027", descripcion: "Evaluar cumplimiento de requisitos legales primer semestre 2027.", responsable: "EHS", inicio: "2027-05-01", fin: "2027-06-30", frecuencia: "Semestral", evidencia: "Informe evaluación", kpi: "% cumplimiento legal", meta: "≥ 90%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "20", eje: "Cumplimiento legal", actividad: "Evaluación legal segundo semestre 2027", descripcion: "Evaluar cumplimiento de requisitos legales segundo semestre 2027.", responsable: "EHS", inicio: "2027-10-01", fin: "2027-11-30", frecuencia: "Semestral", evidencia: "Informe evaluación", kpi: "% cumplimiento legal", meta: "≥ 90%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "21", eje: "Verificación", actividad: "Auditoría interna completa ISO 45001", descripcion: "Auditoría interna completa previo a certificación.", responsable: "EHS / Auditor interno", inicio: "2027-08-01", fin: "2027-09-30", frecuencia: "Anual", evidencia: "Informe de auditoría completo", kpi: "% cláusulas auditadas", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "22", eje: "Revisión gerencial", actividad: "Revisión por la dirección cierre 2026", descripcion: "Revisión gerencial del SG-SST al cierre del año 2026.", responsable: "Alta Dirección / EHS", inicio: "2026-12-01", fin: "2026-12-31", frecuencia: "Anual", evidencia: "Acta de revisión gerencial", kpi: "Revisión realizada", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "23", eje: "Revisión gerencial", actividad: "Revisión por la dirección cierre 2027", descripcion: "Revisión gerencial del SG-SST al cierre del año 2027.", responsable: "Alta Dirección / EHS", inicio: "2027-11-01", fin: "2027-12-31", frecuencia: "Anual", evidencia: "Acta de revisión gerencial", kpi: "Revisión realizada", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "24", eje: "Mejora continua", actividad: "Plan de mejora 2028", descripcion: "Levantar oportunidades y definir plan para el ciclo 2028.", responsable: "EHS / Alta Dirección", inicio: "2027-11-01", fin: "2027-12-31", frecuencia: "Anual", evidencia: "Plan de mejora aprobado", kpi: "Plan elaborado", meta: "Sí", prioridad: "Media", estado: "No iniciado", avance: 0 },
];

const MA = [
  { codigoExterno: "P-001", clausula: "4.1 / 4.3", eje: "Contexto", actividad: "Levantar procesos, actividades e instalaciones con impacto ambiental", responsable: "EHS / Jefaturas", inicio: "2026-08-05", fin: "2026-08-31", frecuencia: "Única", evidencia: "Mapa de procesos ambientales", kpi: "Mapa aprobado", meta: "Sí", prioridad: "Alta", estado: "En curso", avance: 0.5 },
  { codigoExterno: "P-002", clausula: "6.1.2", eje: "Aspectos ambientales", actividad: "Identificar y evaluar aspectos e impactos ambientales", responsable: "EHS / Operaciones", inicio: "2026-08-05", fin: "2026-08-31", frecuencia: "Única", evidencia: "Matriz de aspectos e impactos", kpi: "% áreas evaluadas", meta: "100%", prioridad: "Alta", estado: "En curso", avance: 0.4 },
  { codigoExterno: "P-003", clausula: "6.1.3", eje: "Cumplimiento legal", actividad: "Crear matriz legal ambiental aplicable a la operación en Chile", responsable: "EHS / Legal", inicio: "2026-08-12", fin: "2026-10-15", frecuencia: "Única", evidencia: "Matriz legal ambiental", kpi: "% requisitos identificados", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-004", clausula: "4.2", eje: "Partes interesadas", actividad: "Identificar necesidades y expectativas ambientales de partes interesadas", responsable: "EHS / Gerencia", inicio: "2026-09-01", fin: "2026-09-20", frecuencia: "Única", evidencia: "Matriz de partes interesadas", kpi: "Matriz emitida", meta: "Sí", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-005", clausula: "5.2", eje: "Liderazgo", actividad: "Revisar o emitir política ambiental", responsable: "Gerencia / EHS", inicio: "2026-09-01", fin: "2026-09-30", frecuencia: "Única", evidencia: "Política ambiental publicada", kpi: "Política vigente", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-006", clausula: "6.2", eje: "Objetivos", actividad: "Definir objetivos, metas e indicadores ambientales 2026-2027", responsable: "Gerencia / EHS", inicio: "2026-10-09", fin: "2026-09-30", frecuencia: "Única", evidencia: "Programa ambiental aprobado", kpi: "Objetivos aprobados", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-007", clausula: "8.1", eje: "Residuos", actividad: "Estandarizar segregación, almacenamiento, retiro y trazabilidad de residuos", responsable: "EHS / Operaciones", inicio: "2026-10-01", fin: "2026-10-31", frecuencia: "Mensual", evidencia: "Procedimiento y registros de retiro", kpi: "% retiros con registro", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-008", clausula: "8.1", eje: "Sustancias químicas", actividad: "Revisar inventario, SDS, compatibilidad y contención secundaria", responsable: "EHS / Bodega", inicio: "2026-10-01", fin: "2026-10-31", frecuencia: "Trimestral", evidencia: "Inventario de sustancias y SDS", kpi: "% sustancias con SDS", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-009", clausula: "8.2", eje: "Emergencias ambientales", actividad: "Implementar kits antiderrames y realizar simulacro de derrame", responsable: "EHS / Emergencias", inicio: "2026-11-01", fin: "2026-11-30", frecuencia: "Semestral", evidencia: "Informe de simulacro", kpi: "Nro simulacros realizados", meta: "2", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-010", clausula: "9.1", eje: "Agua", actividad: "Levantar línea base de consumo de agua y puntos de uso críticos", responsable: "EHS / Mantención", inicio: "2026-11-01", fin: "2026-11-30", frecuencia: "Mensual", evidencia: "Línea base de consumo de agua", kpi: "m3/mes", meta: "Medido", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-011", clausula: "9.1", eje: "Energía", actividad: "Levantar línea base de consumo eléctrico y oportunidades de ahorro", responsable: "EHS / Mantención", inicio: "2026-11-01", fin: "2026-11-30", frecuencia: "Mensual", evidencia: "Línea base energética", kpi: "kWh/mes", meta: "Medido", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-012", clausula: "8.1", eje: "Contratistas", actividad: "Incorporar requisitos ambientales en inducción y control de contratistas", responsable: "EHS / Compras", inicio: "2026-12-01", fin: "2026-12-31", frecuencia: "Mensual", evidencia: "Checklist contratistas", kpi: "% contratistas evaluados", meta: "100%", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-013", clausula: "7.5", eje: "Documentación", actividad: "Crear control documental ambiental", responsable: "EHS", inicio: "2026-12-01", fin: "2026-12-31", frecuencia: "Única", evidencia: "Registro maestro documental", kpi: "% documentos controlados", meta: "100%", prioridad: "Media", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-014", clausula: "7.2 / 7.3", eje: "Competencia", actividad: "Ejecutar plan anual de capacitación ambiental", responsable: "EHS / RRHH", inicio: "2027-01-02", fin: "2027-06-30", frecuencia: "Trimestral", evidencia: "Registros de capacitación", kpi: "% personal capacitado", meta: "≥ 80%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-015", clausula: "8.1", eje: "Control operacional", actividad: "Implementar inspecciones ambientales mensuales", responsable: "EHS / Supervisores", inicio: "2027-01-01", fin: "2027-12-31", frecuencia: "Mensual", evidencia: "Registros de inspección", kpi: "% inspecciones realizadas", meta: "≥ 90%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-016", clausula: "9.1", eje: "Indicadores", actividad: "Medir indicadores ambientales y emitir dashboard trimestral", responsable: "EHS", inicio: "2027-01-01", fin: "2027-12-31", frecuencia: "Trimestral", evidencia: "Informe de indicadores", kpi: "Dashboard emitido", meta: "4 al año", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-017", clausula: "9.1.2", eje: "Cumplimiento legal", actividad: "Ejecutar evaluación trimestral de cumplimiento ambiental", responsable: "EHS / Legal", inicio: "2027-03-01", fin: "2027-12-31", frecuencia: "Trimestral", evidencia: "Informe evaluación legal", kpi: "% cumplimiento", meta: "≥ 90%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-018", clausula: "9.2", eje: "Auditoría interna", actividad: "Realizar auditoría interna ISO 14001 primera etapa", responsable: "EHS / Auditor interno", inicio: "2027-05-01", fin: "2027-06-30", frecuencia: "Anual", evidencia: "Informe de auditoría", kpi: "Auditoría realizada", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-019", clausula: "10.2", eje: "Mejora", actividad: "Generar y cerrar plan de acciones correctivas", responsable: "EHS / Áreas", inicio: "2027-01-01", fin: "2027-12-31", frecuencia: "Mensual", evidencia: "Registro CAPA ambiental", kpi: "% CAPA cerradas", meta: "≥ 85%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-020", clausula: "9.3", eje: "Revisión dirección", actividad: "Realizar revisión gerencial ambiental", responsable: "Alta Dirección / EHS", inicio: "2027-07-01", fin: "2027-07-31", frecuencia: "Anual", evidencia: "Acta revisión gerencial", kpi: "Revisión realizada", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-021", clausula: "6.1.2", eje: "Aspectos ambientales", actividad: "Actualizar matriz de aspectos e impactos ambientales", responsable: "EHS / Operaciones", inicio: "2027-08-01", fin: "2027-08-31", frecuencia: "Anual", evidencia: "Matriz actualizada", kpi: "% áreas actualizadas", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-022", clausula: "6.1.3", eje: "Cumplimiento legal", actividad: "Actualizar matriz legal ambiental", responsable: "EHS / Legal", inicio: "2027-08-01", fin: "2027-09-30", frecuencia: "Anual", evidencia: "Matriz actualizada", kpi: "% requisitos actualizados", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-023", clausula: "9.2", eje: "Auditoría interna", actividad: "Realizar segundo ciclo de auditoría interna ISO 14001", responsable: "EHS / Auditor interno", inicio: "2027-09-01", fin: "2027-10-31", frecuencia: "Anual", evidencia: "Informe de auditoría completo", kpi: "Auditoría realizada", meta: "Sí", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-024", clausula: "10.2", eje: "Mejora", actividad: "Cerrar no conformidades y oportunidades de mejora 2027", responsable: "EHS / Áreas", inicio: "2027-10-01", fin: "2027-11-30", frecuencia: "Única", evidencia: "Registro cierre NC", kpi: "% NC cerradas", meta: "100%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-025", clausula: "9.1", eje: "Desempeño ambiental", actividad: "Evaluar cumplimiento anual de objetivos e indicadores ambientales", responsable: "EHS / Gerencia", inicio: "2027-11-01", fin: "2027-11-30", frecuencia: "Anual", evidencia: "Informe anual ambiental", kpi: "% objetivos cumplidos", meta: "≥ 80%", prioridad: "Alta", estado: "No iniciado", avance: 0 },
  { codigoExterno: "P-026", clausula: "6.2", eje: "Planificación 2028", actividad: "Definir programa ambiental 2028", responsable: "EHS / Gerencia", inicio: "2027-11-01", fin: "2027-12-31", frecuencia: "Anual", evidencia: "Programa aprobado", kpi: "Programa elaborado", meta: "Sí", prioridad: "Media", estado: "No iniciado", avance: 0 },
];

export async function POST(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token");
  if (!TOKEN || token !== TOKEN) {
    return NextResponse.json({ error: "No autorizado" }, { status: 403 });
  }

  await prisma.planActividad.deleteMany({ where: { programa: { in: ["SST", "MA"] } } });

  for (const a of SST) {
    await prisma.planActividad.create({
      data: { programa: "SST", codigoExterno: a.codigoExterno, eje: a.eje, actividad: a.actividad, descripcion: a.descripcion, responsable: a.responsable, inicio: new Date(a.inicio), fin: new Date(a.fin), frecuencia: a.frecuencia, evidencia: a.evidencia, kpi: a.kpi, meta: a.meta, prioridad: a.prioridad, estado: a.estado, avance: a.avance },
    });
  }

  for (const a of MA) {
    await prisma.planActividad.create({
      data: { programa: "MA", codigoExterno: a.codigoExterno, clausula: a.clausula, eje: a.eje, actividad: a.actividad, responsable: a.responsable, inicio: new Date(a.inicio), fin: new Date(a.fin), frecuencia: a.frecuencia, evidencia: a.evidencia, kpi: a.kpi, meta: a.meta, prioridad: a.prioridad, estado: a.estado, avance: a.avance },
    });
  }

  return NextResponse.json({ ok: true, sst: SST.length, ma: MA.length });
}
